# Config
# ========================================================================================

lang:        en
title:       Ben Banks
description: >
  Payments, digital, and tinkering — the personal site of Ben Banks.

url: https://bencbanks.github.io

author:
  name:  Ben Banks
  email: Ben@theBanks.io

permalink: /:year/:month/:day/:title/

# Collections
collections:
  featured_tags:
    permalink: /tag-:name/
    output:    true

# SEO / social
social:
  name: Ben Banks
  links:
    - https://www.linkedin.com/in/benjamin-banks

# Plugins
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Plugin config
optional_front_matter:
  remove_originals: true

relative_links:
  collections: true

titles_from_headings:
  strip_title:  true
  collections:  true

# Build
exclude:
  - .jekyll-cache
  - .sass-cache
  - .ruby-lsp
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - '*.toml'
include:
  - .well-known

sass:
  style: compressed
